### ISSUE TITLE
Additional PostHTML plugins to use - config and usage instructions

### ISSUE THREAD

**Issue by laurenhitchon** [vituum/vite-plugin-posthtml#3]
Hello, 

I would like to use the 'posthtml-components' plugin https://github.com/thewebartisan7/posthtml-components but I am having trouble getting it to work with vituum and the vite-plugin-posthtml plugin.

Have you been able to install and use post-html plugins together with vituum and the vite-plugin-posthtml and if so what should I be adding to vite.config.js.

Many thanks

**Comment by lubomirblazekcz** [comment]
You should be able to add it via https://vituum.dev/plugins/posthtml.html#plugins in config
